# -*- coding: utf-8 -*-
"""MainE1 v0.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_9LBluA6Cuj2qmOXlwj1NUSDmNBPh6I
"""

from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI
from getpass import getpass
import os

os.environ["CREWAI_TRACING_ENABLED"] = "False"

os.environ["OPENAI_API_KEY"] = getpass("OpenAI key → ")

llm = ChatOpenAI(model="gpt-5.1", temperature=0.0)

# ===================================
# LOWER LAYER — The 6 Sub-Personalities
# ===================================
creative       = Agent(role="Creative Clarity",        goal="Clear ideation",          backstory="Tone: clear, concise, factual. No fluff. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False)
structural     = Agent(role="Structural Clarity",      goal="Relieve overload",        backstory="Tone: non-judgmental, reflective, straightforward. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False)
alignment      = Agent(role="Self-Alignment",         goal="Goal coherence",          backstory="Tone: sharp, minimal, focused. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False)
decision       = Agent(role="Decision Support",       goal="Structured decisions",    backstory="Tone: tactical, calm, analytical. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False)
recovery       = Agent(role="Recovery Management",    goal="Pressure relief",         backstory="Tone: firm yet empathetic. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False)
boundary       = Agent(role="Boundary Clarity",       goal="Define limits",          backstory="Tone: steady, respectful, firm. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False)

sub_personalities = [creative, structural, alignment, decision, recovery, boundary]

# ===================================
# UPPER LAYER — Central Synthesizer (N2 + ODAI built in)
# ===================================
central = Agent(
    role="Central Consciousness",
    goal="Produce one unified, perfect response",
    backstory="""You receive the outputs of exactly 6 sub-personalities.
You never reveal their names or internal process.
You run ODAI once:

Observation  → what actually needs to be answered
Distillation → core truth + alignment score 0–10
Adaptation   → if score <8, write precise repair instructions for the swarm
Integration  → if score ≥8, write the final answer in clean markdown

Never mention score, agents, SIM, ODAI, or process in output.
If score ≥8, output ONLY the final answer in clean markdown with real line breaks. Nothing else.
If score <8, output ONLY the repair instructions in structured plain text. Nothing else.
Never output JSON.""",
    llm=ChatOpenAI(model="gpt-5.1", temperature=0.0),
    verbose=False
)

# ===================================
# MAIN LOOP — Pure MainE1 Architecture
# ===================================
print("\nMainE1 — True Hierarchical Architecture — November 2025 — Clean v0.1\n")

history = ""

while True:
    query = input("QUERY → ").strip()
    if query.lower() in {"exit", "quit", ""}:
        break

    # LOWER LAYER — parallel execution
    tasks = [Task(description=query + "\n\n" + history, expected_output="Exactly 4 numbered SIM lines only.", agent=agent) for agent in sub_personalities]
    swarm = Crew(agents=sub_personalities, tasks=tasks, process=Process.sequential, verbose=False)  # sequential is fine for 6 agents
    raw_contributions = swarm.kickoff().raw

    # UPPER LAYER — synthesis + N2
    synth_task = Task(
        description=f"User query: {query}\nSub-personality contributions:\n{raw_contributions}",
        expected_output="Strict JSON with keys: score, repair, final",
        agent=central
    )

    for attempt in range(1, 5):
        result = Crew(agents=[central], tasks=[synth_task], verbose=False).kickoff().raw

        # Force JSON
        if "{" not in result:
            continue

        try:
            data = eval(result.strip())  # safe because we control expected_output
            if data["score"] >= 9:
                print((data.get("final") or data.get("synthesis") or result).strip())
                history += f"\nUser: {query}\nMainE1: {(data.get('final') or '').strip()}"
                break
            else:
                # Real N2 repair loop
                print(f"\n[N2 rejection — score {data['score']}/10 — re-running swarm with repair]")
                repair_tasks = [Task(description=query + "\nREPAIR DIRECTIVE: " + data["repair"], expected_output="Exactly 4 numbered SIM lines only.", agent=agent) for agent in sub_personalities]
                raw_contributions = Crew(agents=sub_personalities, tasks=repair_tasks, verbose=False).kickoff()
                synth_task.description = f"User query: {query}\nNew contributions after repair:\n{raw_contributions}"
        except:
            continue
    else:
        # Even when it says "Max attempts", the JSON is still there → extract final
            try:
                data = eval(result.strip())
                print((data.get("final") or data.get("synthesis") or result).strip())
            except:
                print(result.strip())

    print("\n" + "—" * 80)

